/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function bundle(options: BundleDtsOptions): BundleDtsResult;

export interface BundleDtsDiagnostic {
  message: string;
  file?: string;
  span?: Array<number>;
  severity: string;
}

export interface BundleDtsOptions {
  input: Array<string>;
  external?: Array<string>;
  cwd?: string;
  sourcemap?: boolean;
  cjsDefault?: boolean;
}

export interface BundleDtsResult {
  code: string;
  map?: string;
  warnings: Array<BundleDtsDiagnostic>;
}

/**
 * Run the CLI with the given argv (pass `process.argv`; argv[0] and argv[1] are skipped).
 *
 * All output is written to stdout/stderr and the process exits when done.
 */
export declare function cli(argv: Array<string>): void;
